networks:
  transferNet:
    driver: bridge
    
services:
  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5030:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - transferNet
      
  api:
    #build: ./WebApiTransfer
    image: novakvova/stransfer-api:latest
    depends_on:
      - db
    ports:
      - "6789:8080"
    networks:
      - transferNet
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    volumes:
      - api_data:/app/Images


  frontend:
    #build: ./my-transfer
    image: novakvova/stransfer-react:latest
    ports:
      - "3421:80"
    env_file: 
      - .env
      
volumes:
  db_data:
  api_data:

