services:
  api:
    build: ./WebApiTransfer
    ports:
      - "5898:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5028;Database=mybober;Username=bober;Password=mimi45Wh--xaxalala;
    depends_on:
       db:
         condition: service_healthy
        
    volumes:
      - api_data:/app/data
      - ./WebApiTransfer/Public/Images:/app/Public/Images

  frontend:
    build: ./my-transfer
    ports:
      - "3987:80"
    volumes:
      - ./my-transfer/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: bober
      POSTGRES_PASSWORD: mimi45Wh--xaxalala
      POSTGRES_DB: mybober
    ports:
      - "5028:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siuzanna -d mybankomat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  api_data:
